fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, priorities: [ 'json', '*/*'], fallback_format: ~, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    exception:
        enabled: true
        serialize_exceptions: false
        messages:
            Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
            Symfony\Component\HttpKernel\Exception\NotFoundHttpException: true