version: '3'

services:
  database:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE:  db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
    - dbdata:/var/lib/mysql/
    networks:
      - backend_private
  app:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
      - nginx
    networks:
      - backend_private
  nginx:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - backend_private
      - backend_public

volumes:
  dbdata:
    driver: local

networks:
  backend_private:
  backend_public: